package com.example.PostalCodeValidator.enums;

import lombok.Getter;

@Getter
public enum CountryCode {
    ANDORRA("AD"),
    ARGENTINA("AR"),
    AMERICAN_SAMOA("AS"),
    AUSTRIA("AT"),
    AUSTRALIA("AU"),
    BANGLADESH("BD"),
    BELGIUM("BE"),
    BULGARIA("BG"),
    BRAZIL("BR"),
    CANADA("CA"),
    SWITZERLAND("CH"),
    CZECH_REPUBLIC("CZ"),
    GERMANY("DE"),
    DENMARK("DK"),
    DOMINICAN_REPUBLIC("DO"),
    SPAIN("ES"),
    FINLAND("FI"),
    FAROE_ISLANDS("FO"),
    FRANCE("FR"),
    UNITED_KINGDOM("GB"),
    FRENCH_GUYANA("GF"),
    GUERNSEY("GG"),
    GREENLAND("GL"),
    GUADELOUPE("GP"),
    GUATEMALA("GT"),
    GUAM("GU"),
    GUYANA("GY"),
    CROATIA("HR"),
    HUNGARY("HU"),
    ISLE_OF_MAN("IM"),
    INDIA("IN"),
    ICELAND("IS"),
    ITALY("IT"),
    JERSEY("JE"),
    JAPAN("JP"),
    LIECHTENSTEIN("LI"),
    SRI_LANKA("LK"),
    LITHUANIA("LT"),
    LUXEMBOURG("LU"),
    MONACO("MC"),
    MOLDAVIA("MD"),
    MARSHALL_ISLANDS("MH"),
    MACEDONIA("MK"),
    NORTHERN_MARIANA_ISLANDS("MP"),
    MARTINIQUE("MQ"),
    MEXICO("MX"),
    MALAYSIA("MY"),
    HOLLAND("NL"),
    NORWAY("NO"),
    NEW_ZEALAND("NZ"),
    PHILIPPINES("PH"),
    PAKISTAN("PK"),
    POLAND("PL"),
    SAINT_PIERRE_AND_MIQUELON("PM"),
    PUERTO_RICO("PR"),
    PORTUGAL("PT"),
    FRENCH_REUNION("RE"),
    RUSSIA("RU"),
    SWEDEN("SE"),
    SLOVENIA("SI"),
    SVALBARD_JAN_MAYEN("SJ"),
    SLOVAK_REPUBLIC("SK"),
    SAN_MARINO("SM"),
    THAILAND("TH"),
    TURKEY("TR"),
    UNITED_STATES("US"),
    VATICAN("VA"),
    VIRGIN_ISLANDS("VI"),
    MAYOTTE("YT"),
    SOUTH_AFRICA("ZA");

    private final String code;

    CountryCode(String code) {
        this.code = code;
    }

}
